name: tree_state_router_examples
description: "Examples of using the tree_state_router package"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logging: ^1.2.0
  tree_state_machine: ^3.0.0-dev.12
  # tree_state_machine:
  #   path: ../../tree_state_machine
  tree_state_router:
    path: ..


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
