name: tree_state_router
description: "Flutter navigation and routing based on hierarchical state machines"
version: 0.0.1-dev.3
homepage: https://github.com/jlewicki/tree_state_router
#publish_to: 'none'

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  logging: ^1.2.0
  tree_state_machine: ^3.0.0-dev.12
  # tree_state_machine:
  #   path: ../tree_state_machine

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.3

flutter:
