name: tree_state_router
description: "Flutter navigation and routing based on hierarchical state machines"
version: 0.0.1-dev.1
homepage: https://github.com/jlewicki/tree_state_router

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  tree_state_machine: ^3.0.0-dev.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.3

flutter:
